config/routes.rb
Rails.application.routes.draw do
  
  resources :brands
  resources :certificates
  get 'information/index'

  get 'slave/index'

  resources :group4s
  resources :group3s
  resources :group2s
  resources :group1s
  devise_for :users
  get 'company/index'

  root 'welcome#index'
  
  get '/projects/:id', to: 'clients#show'
  get '/pages/portfolios', to: 'clients#index'
  
  get 'welcome/index'

  resources :prices
  resources :reviews
  resources :clients
  resources :sliders
  resources :pages
  resources :contents
  resources :messages

  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  dragonfly_accessor :image
  dragonfly_accessor :image1
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/client.rb
class Client < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/group1.rb
class Group1 < ActiveRecord::Base
  has_many :group2

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group2.rb
class Group2 < ActiveRecord::Base
  belongs_to :group1
  has_many :group3
  
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group3.rb
class Group3 < ActiveRecord::Base
  belongs_to :group2
  has_many :group4

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group4.rb
class Group4 < ActiveRecord::Base
  belongs_to :group3
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :description, :slave, :image_uid, :image_name, :url, :sort)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/group1s_helper.rb
module Group1sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/slave_helper.rb
module SlaveHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :slave %><br>
    <%= f.text_area :slave %>
  </div>
  <div class="field">
    <%= f.label :image_uid %><br>
    <%= f.text_field :image_uid %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.number_field :sort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Slave</th>
      <th>Image uid</th>
      <th>Image name</th>
      <th>Url</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.description %></td>
        <td><%= content.slave %></td>
        <td><%= content.image_uid %></td>
        <td><%= content.image_name %></td>
        <td><%= content.url %></td>
        <td><%= content.sort %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @content.description %>
</p>

<p>
  <strong>Slave:</strong>
  <%= @content.slave %>
</p>

<p>
  <strong>Image uid:</strong>
  <%= @content.image_uid %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @content.image_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @content.url %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @content.sort %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>