config/routes.rb
Rails.application.routes.draw do
  
  resources :brands
  resources :certificates
  get 'information/index'

  get 'slave/index'

  resources :group4s
  resources :group3s
  resources :group2s
  resources :group1s
  devise_for :users
  get 'company/index'

  root 'welcome#index'
  
  get '/projects/:id', to: 'clients#show'
  get '/pages/portfolios', to: 'clients#index'
  
  get 'welcome/index'

  resources :prices
  resources :reviews
  resources :clients
  resources :sliders
  resources :pages
  resources :contents
  resources :messages

  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  dragonfly_accessor :image
  dragonfly_accessor :image1
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/client.rb
class Client < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/group1.rb
class Group1 < ActiveRecord::Base
  has_many :group2

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group2.rb
class Group2 < ActiveRecord::Base
  belongs_to :group1
  has_many :group3
  
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group3.rb
class Group3 < ActiveRecord::Base
  belongs_to :group2
  has_many :group4

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group4.rb
class Group4 < ActiveRecord::Base
  belongs_to :group3
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
    @page=@price

    @html = case true
    when @page.cartridge
      @footerprice.description
    when @page.utilize
      @utilize.slave
    else
      @footerprice.description.html_safe
    end
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:title, :description, :slave, :image_uid, :image_name, :url, :sort)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/group1s_helper.rb
module Group1sHelper
end

app/helpers/group2s_helper.rb
module Group2sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/slave_helper.rb
module SlaveHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :slave %><br>
    <%= f.text_area :slave %>
  </div>
  <div class="field">
    <%= f.label :image_uid %><br>
    <%= f.text_field :image_uid %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.number_field :sort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Slave</th>
      <th>Image uid</th>
      <th>Image name</th>
      <th>Url</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.title %></td>
        <td><%= price.description %></td>
        <td><%= price.slave %></td>
        <td><%= price.image_uid %></td>
        <td><%= price.image_name %></td>
        <td><%= price.url %></td>
        <td><%= price.sort %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<%= render 'shared/page'%>
<section id="pageWrap" style="margin-top: -90px">
  <div class="container">

    <div class="page-text">
      <%= @html.html_safe %>
    </div>
  </div>
</section> 