config/routes.rb
Rails.application.routes.draw do
  
  resources :brands
  resources :certificates
  get 'information/index'

  get 'slave/index'

  resources :group4s
  resources :group3s
  resources :group2s
  resources :group1s
  devise_for :users
  get 'company/index'

  root 'welcome#index'
  
  get '/projects/:id', to: 'clients#show'
  get '/pages/portfolios', to: 'clients#index'
  
  get 'welcome/index'

  resources :prices
  resources :reviews
  resources :clients
  resources :sliders
  resources :pages
  resources :contents
  resources :messages

  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  dragonfly_accessor :image
  dragonfly_accessor :image1
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/client.rb
class Client < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/group1.rb
class Group1 < ActiveRecord::Base
  has_many :group2

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group2.rb
class Group2 < ActiveRecord::Base
  belongs_to :group1
  has_many :group3
  
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group3.rb
class Group3 < ActiveRecord::Base
  belongs_to :group2
  has_many :group4

  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/group4.rb
class Group4 < ActiveRecord::Base
  belongs_to :group3
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    #exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Certificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:title, :description, :slave, :image_uid, :image_name, :url, :sort)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/group1s_helper.rb
module Group1sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/slave_helper.rb
module SlaveHelper
end

app/views/certificates/_form.html.erb
<%= form_for(@certificate) do |f| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% @certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :slave %><br>
    <%= f.text_area :slave %>
  </div>
  <div class="field">
    <%= f.label :image_uid %><br>
    <%= f.text_field :image_uid %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.number_field :sort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Editing Certificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<section id="information">
  <div id='pageWrap'>
    <div class="page-header">
      <span><a href="/">На главную</a> <strong> >> </strong> СЕРТИФИКАТЫ</span>
    </div>
  </div>
  <% content_for :title, " | сертифицированный сервисный центр в Липецке | СЕРТИФИКАТЫ Инженеров | СЕРТИФИКАТЫ Компании Диджитал Сервис " %>
  <div class="page-text container-fluid">
      <legend><h2 class="block-title">
        <span><b>Диджитал</b> сервис</span> <small><a href="javascript:void(0);">сертифицированный центр</a></small>
      </h2></legend>
      <div class="content">
        <h2>Сертификаты компании</h2>
        <hr>
        <div class='row'>
        <%count=0;@cert_company.sort_by(&:sort).each do |cert| %>
        <%= count>=4? (count=1;'</div><div class="row">'.html_safe) : (count+=1;'') %>
          <div class="col-sm-3">
            <%= image_tag cert.image.url, class: 'img-responsive gallery-img',alt: cert.title if cert.image_stored? %>
          </div>
        <%end%>
        </div>
        <h2>Сертификаты инженеров</h2>
        <hr>
        <div class='row'>
        <%count=0;@cert_people.sort_by(&:sort).each do |cert| %>
        <%= count>=4? (count=1;'</div><div class="row">'.html_safe) : (count+=1;'') %>
          <div class="col-sm-3">
            <%= image_tag cert.image.url, class: 'img-responsive gallery-img',alt: cert.title if cert.image_stored? %>
          </div>
        <%end%>
        </div>  
      </div>
  </div>
</section>

app/views/certificates/new.html.erb
<h1>New Certificate</h1>

<%= render 'form' %>

<%= link_to 'Back', certificates_path %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @certificate.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @certificate.description %>
</p>

<p>
  <strong>Slave:</strong>
  <%= @certificate.slave %>
</p>

<p>
  <strong>Image uid:</strong>
  <%= @certificate.image_uid %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @certificate.image_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @certificate.url %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @certificate.sort %>
</p>

<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>